### PR TITLE
Venus seams nice destination

### PR DESCRIPTION
**Pull request by mkuzak**

### CODE REVIEW

**Comment by c-martinez** [comment]
I'm not sure? do they have good food?

**Comment by mkuzak** [comment]
I heard they have nice sushi places.

**Comment by c-martinez** [comment]
Good, can you suggest a few (and make a commit for it)

**Comment by mkuzak** [comment]
Should I add it to same file? I'd suggest create new file for that

**Comment by c-martinez** [comment]
Do a new file. thanks

**Pull request merged**
